/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    company: Company;
    investment: Investment;
    investmentRecommendation: InvestmentRecommendation;
    investors: Investor;
    'option-opportunities': OptionOpportunity;
    'option-paper-trades': OptionPaperTrade;
    'option-alerts': OptionAlert;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    company: CompanySelect<false> | CompanySelect<true>;
    investment: InvestmentSelect<false> | InvestmentSelect<true>;
    investmentRecommendation: InvestmentRecommendationSelect<false> | InvestmentRecommendationSelect<true>;
    investors: InvestorsSelect<false> | InvestorsSelect<true>;
    'option-opportunities': OptionOpportunitiesSelect<false> | OptionOpportunitiesSelect<true>;
    'option-paper-trades': OptionPaperTradesSelect<false> | OptionPaperTradesSelect<true>;
    'option-alerts': OptionAlertsSelect<false> | OptionAlertsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "company".
 */
export interface Company {
  id: number;
  name: string;
  ticker: string;
  recommendationDate: string;
  bullCase?:
    | {
        opinionText: string;
        opinionDate: string;
        id?: string | null;
      }[]
    | null;
  bearCase?:
    | {
        opinionText: string;
        opinionDate: string;
        id?: string | null;
      }[]
    | null;
  priceTarget?: number | null;
  currentPrice?: number | null;
  timeframe?: string | null;
  ytdReturn?: number | null;
  weekToDateReturn?: number | null;
  oneYearReturn?: number | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "investment".
 */
export interface Investment {
  id: number;
  accountType: 'taxable' | 'ira';
  investorMapping: number | Investor;
  company: number | Company;
  transactionType: 'buy' | 'sell';
  investmentDate: string;
  shares: number;
  pricePerShare: number;
  notes?: string | null;
  displayTitle?: string | null;
  investor?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "investors".
 */
export interface Investor {
  id: number;
  email: string;
  firstName?: string | null;
  lastName?: string | null;
  password: string;
  investableAssets?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "investmentRecommendation".
 */
export interface InvestmentRecommendation {
  id: number;
  investor: number | Investor;
  company: number | Company;
  recommendationDate: string;
  buySellHoldRecommendation: 'buy' | 'sell' | 'hold';
  recommendationReasoning: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "option-opportunities".
 */
export interface OptionOpportunity {
  id: number;
  opportunityId: string;
  /**
   * Stock ticker symbol (e.g., SNOW, OKTA, ZS)
   */
  ticker: string;
  /**
   * Full company name
   */
  companyName?: string | null;
  /**
   * Investor who owns this opportunity
   */
  investor: number | Investor;
  /**
   * Date of earnings announcement
   */
  earningsDate: string;
  /**
   * When this opportunity was found by scanner
   */
  identifiedDate: string;
  /**
   * Post-earnings price drop percentage (e.g., -14.7)
   */
  dropPct: number;
  /**
   * How much earnings beat estimates (e.g., +12.5)
   */
  epsBeatPct: number;
  /**
   * Composite score (0-100). 85+ = Strong trade signal, 70-84 = Consider
   */
  score: number;
  /**
   * Stock price before earnings
   */
  preEarningsPrice?: number | null;
  /**
   * Stock price after earnings drop
   */
  postEarningsPrice?: number | null;
  /**
   * Latest stock price
   */
  currentPrice?: number | null;
  /**
   * Market capitalization in dollars
   */
  marketCap?: number | null;
  /**
   * Stock sector (Tech preferred for this strategy)
   */
  sector?: ('technology' | 'communication' | 'healthcare' | 'financial' | 'consumer' | 'other') | null;
  /**
   * Opportunity lifecycle status
   */
  status: 'pending' | 'traded' | 'dismissed' | 'expired';
  /**
   * Trading strategy name
   */
  strategy?: string | null;
  /**
   * Additional notes or observations
   */
  notes?: string | null;
  displayTitle?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "option-paper-trades".
 */
export interface OptionPaperTrade {
  id: number;
  tradeId: string;
  /**
   * Stock ticker symbol
   */
  ticker: string;
  /**
   * Investor who owns this trade
   */
  investor: number | Investor;
  /**
   * Link to the opportunity that triggered this trade
   */
  opportunity?: (number | null) | OptionOpportunity;
  /**
   * Original earnings date
   */
  earningsDate: string;
  /**
   * When opportunity was identified
   */
  identifiedDate: string;
  /**
   * Post-earnings price drop %
   */
  dropPct: number;
  /**
   * EPS beat magnitude %
   */
  epsBeatPct: number;
  /**
   * Original opportunity score (0-100)
   */
  score: number;
  /**
   * When position was entered
   */
  entryDate?: string | null;
  /**
   * Stock price when entering position
   */
  stockPriceAtEntry?: number | null;
  /**
   * ATM strike price of call option
   */
  strikePrice?: number | null;
  /**
   * Premium paid per contract (e.g., $3.80)
   */
  entryPremium?: number | null;
  /**
   * Number of option contracts (each = 100 shares)
   */
  contracts: number;
  /**
   * Days to expiration when entered (typically 30-45)
   */
  dteAtEntry?: number | null;
  /**
   * When position was closed
   */
  exitDate?: string | null;
  /**
   * Stock price when closing position
   */
  stockPriceAtExit?: number | null;
  /**
   * Premium received per contract when selling
   */
  exitPremium?: number | null;
  /**
   * Why was this position closed?
   */
  exitReason?: ('profit_target' | 'stop_loss' | 'time_stop' | 'day1_circuit_breaker' | 'manual') | null;
  /**
   * Current position status
   */
  status: 'pending' | 'open' | 'closed' | 'cancelled';
  /**
   * Percentage of account allocated (e.g., 2.0 = 2%)
   */
  positionSizePct?: number | null;
  /**
   * Calculated: (exitPremium - entryPremium) * contracts * 100
   */
  pnlDollars?: number | null;
  /**
   * Calculated: ((exitPremium - entryPremium) / entryPremium) * 100
   */
  pnlPercent?: number | null;
  /**
   * Days between entry and exit
   */
  holdingDays?: number | null;
  /**
   * Trading strategy name
   */
  strategy?: string | null;
  /**
   * Trade notes and observations
   */
  notes?: string | null;
  displayTitle?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "option-alerts".
 */
export interface OptionAlert {
  id: number;
  /**
   * Investor who owns this alert configuration
   */
  investor: number | Investor;
  /**
   * Type of event that triggers this alert
   */
  alertType: 'new_opportunity' | 'profit_target' | 'stop_loss' | 'position_update' | 'daily_summary';
  /**
   * Only alert on opportunities with score >= this value (for new_opportunity alerts)
   */
  minScore?: number | null;
  /**
   * How to deliver this alert (can select multiple)
   */
  deliveryMethods: {
    method: 'email' | 'in_app';
    id?: string | null;
  }[];
  /**
   * Email address for delivery (only shown if Email is selected)
   */
  emailAddress?: string | null;
  /**
   * Turn this alert on or off
   */
  enabled?: boolean | null;
  /**
   * Last time this alert was sent
   */
  lastTriggered?: string | null;
  /**
   * Number of times this alert has been triggered
   */
  triggerCount?: number | null;
  displayTitle?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'company';
        value: number | Company;
      } | null)
    | ({
        relationTo: 'investment';
        value: number | Investment;
      } | null)
    | ({
        relationTo: 'investmentRecommendation';
        value: number | InvestmentRecommendation;
      } | null)
    | ({
        relationTo: 'investors';
        value: number | Investor;
      } | null)
    | ({
        relationTo: 'option-opportunities';
        value: number | OptionOpportunity;
      } | null)
    | ({
        relationTo: 'option-paper-trades';
        value: number | OptionPaperTrade;
      } | null)
    | ({
        relationTo: 'option-alerts';
        value: number | OptionAlert;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "company_select".
 */
export interface CompanySelect<T extends boolean = true> {
  name?: T;
  ticker?: T;
  recommendationDate?: T;
  bullCase?:
    | T
    | {
        opinionText?: T;
        opinionDate?: T;
        id?: T;
      };
  bearCase?:
    | T
    | {
        opinionText?: T;
        opinionDate?: T;
        id?: T;
      };
  priceTarget?: T;
  currentPrice?: T;
  timeframe?: T;
  ytdReturn?: T;
  weekToDateReturn?: T;
  oneYearReturn?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "investment_select".
 */
export interface InvestmentSelect<T extends boolean = true> {
  accountType?: T;
  investorMapping?: T;
  company?: T;
  transactionType?: T;
  investmentDate?: T;
  shares?: T;
  pricePerShare?: T;
  notes?: T;
  displayTitle?: T;
  investor?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "investmentRecommendation_select".
 */
export interface InvestmentRecommendationSelect<T extends boolean = true> {
  investor?: T;
  company?: T;
  recommendationDate?: T;
  buySellHoldRecommendation?: T;
  recommendationReasoning?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "investors_select".
 */
export interface InvestorsSelect<T extends boolean = true> {
  email?: T;
  firstName?: T;
  lastName?: T;
  password?: T;
  investableAssets?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "option-opportunities_select".
 */
export interface OptionOpportunitiesSelect<T extends boolean = true> {
  opportunityId?: T;
  ticker?: T;
  companyName?: T;
  investor?: T;
  earningsDate?: T;
  identifiedDate?: T;
  dropPct?: T;
  epsBeatPct?: T;
  score?: T;
  preEarningsPrice?: T;
  postEarningsPrice?: T;
  currentPrice?: T;
  marketCap?: T;
  sector?: T;
  status?: T;
  strategy?: T;
  notes?: T;
  displayTitle?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "option-paper-trades_select".
 */
export interface OptionPaperTradesSelect<T extends boolean = true> {
  tradeId?: T;
  ticker?: T;
  investor?: T;
  opportunity?: T;
  earningsDate?: T;
  identifiedDate?: T;
  dropPct?: T;
  epsBeatPct?: T;
  score?: T;
  entryDate?: T;
  stockPriceAtEntry?: T;
  strikePrice?: T;
  entryPremium?: T;
  contracts?: T;
  dteAtEntry?: T;
  exitDate?: T;
  stockPriceAtExit?: T;
  exitPremium?: T;
  exitReason?: T;
  status?: T;
  positionSizePct?: T;
  pnlDollars?: T;
  pnlPercent?: T;
  holdingDays?: T;
  strategy?: T;
  notes?: T;
  displayTitle?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "option-alerts_select".
 */
export interface OptionAlertsSelect<T extends boolean = true> {
  investor?: T;
  alertType?: T;
  minScore?: T;
  deliveryMethods?:
    | T
    | {
        method?: T;
        id?: T;
      };
  emailAddress?: T;
  enabled?: T;
  lastTriggered?: T;
  triggerCount?: T;
  displayTitle?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}